import os
import re

from datetime import (
    datetime,
    timezone,
)

def safe_name(value):
    return re.sub(
        r"[^a-zA-Z0-9_-]+",
        "-",
        value,
    ).strip("-")


def generate_report(
    repo,
    issue_number,
    result,
):
    os.makedirs(
        "reports",
        exist_ok=True,
    )

    repo_name = safe_name(
        repo.split("/")[-1]
    )

    timestamp = (
        datetime.now(timezone.utc)
        .strftime(
            "%Y-%m-%d_%H-%M-%S"
        )
    )

    filename = (
        f"{repo_name}-issue-"
        f"{issue_number}-"
        f"{timestamp}.md"
    )

    path = os.path.join(
        "reports",
        filename,
    )

    lines = [
        "# RepoScout Investigation Report",
        "",
        f"**Repository:** `{repo}`",
        f"**Issue:** #{issue_number}",
        (
            "**Generated:** "
            f"{datetime.now(timezone.utc).isoformat()}"
        ),
        "",
        "---",
        "",
        "## Issue Summary",
        "",
        result.issue_summary,
        "",
        "## Likely Root Cause",
        "",
        result.likely_root_cause,
        "",
        (
            f"**Confidence:** "
            f"{result.confidence}"
        ),
        "",
        "## Analysis",
        "",
        result.explanation,
        "",
        "## Evidence",
        "",
    ]

    if result.evidence:

        for index, item in enumerate(
            result.evidence,
            start=1,
        ):
            lines.append(
                f"### {index}. {item.source}"
            )

            lines.append("")

            lines.append(
                f"**Type:** {item.source_type}"
            )

            lines.append("")

            lines.append(
                item.finding
            )

            lines.append("")

            if item.url:
                lines.append(
                    f"[View source]({item.url})"
                )

                lines.append("")

    else:
        lines.extend([
            "No strong supporting evidence "
            "was identified.",
            "",
        ])

    lines.extend([
        "## Suggested Next Steps",
        "",
    ])

    for step in (
        result.suggested_next_steps
    ):
        lines.append(
            f"- {step}"
        )

    lines.extend([
        "",
        "## Limitations",
        "",
    ])

    if result.limitations:

        for limitation in result.limitations:
            lines.append(
                f"- {limitation}"
            )

    else:
        lines.append(
            "- No additional limitations reported."
        )

    lines.extend([
        "",
        "---",
        "",
        (
            "*Generated by RepoScout. "
            "The analysis is advisory and should "
            "be verified by a human maintainer.*"
        ),
    ])

    with open(
        path,
        "w",
        encoding="utf-8",
    ) as file:

        file.write(
            "\n".join(lines)
        )

    return path